### ISSUE TITLE
[ERROR] Making new certificate manager: could not save user: mkdir /etc/ssl/caddy/acme: read-only file system

### ISSUE THREAD

**Issue by SunDevil68** [233boy/v2ray#347] opened 2019-10-04 14:40 UTC
使用233大神的腳本好像也將近兩年了，真的是好東西。最近半年為了騙過長城，用了WS+TLS的選項，安裝有時成功，有時失敗。看log，雖然知道是證書申請不成功導致，總出現這行刺眼的信息：

[ERROR] Making new certificate manager: could not save user: mkdir /etc/ssl/caddy/acme: read-only file system

無奈自己是個小白，很長時間不知道這是什麼原因造成，只能在VPS上不斷重裝系統試錯，Debian 7/8/9、Ubuntu 16.04，到上週搞了CentOS 7，但都不成功，還試著改用Caddy的官方一鍵安裝腳本，也是不行。直到看到下面兩篇教學，試著把systemd用的caddy.service文檔裡的ReadWritePaths=/etc/ssl/caddy改成ReadWriteDirectories=/etc/ssl/caddy，然後證書申請就通過了。如果也是碰到同樣問題的朋友，不妨試試。

https://www.coldawn.com/%e5%9c%a8oracle-cloud%e5%85%8d%e8%b4%b9vps-centos-7-%e7%b3%bb%e7%bb%9f%e4%b8%8a%e5%ae%89%e8%a3%85web%e6%9c%8d%e5%8a%a1%e5%99%a8caddy/

https://github.com/caddyserver/caddy/pull/2620

**Comment by tspring95** [comment] 2019-10-05 00:48
这个牛。方便简单快捷：）

**Comment by 233boy** [comment] 2019-10-05 03:05
@SunDevil68 
感谢你的研究 👍 
看来我觉得很有可能就是这个地方出问题了，但是我自己的测试，我总不能复现这种问题，每次都直接成功。
Caddy 无法正常启动这个问题，经常有人反馈，我也实在无奈 😂 

然后新脚本，我已经自己手动写了 Caddy 的 service，其实你如果更新了脚本，是不会再出现这种问题的了，我将 Caddy 申请的证书放到 /root/.caddy

**Comment by SunDevil68** [comment] 2019-10-05 09:55
> 然后新脚本，我已经自己手动写了 Caddy 的 service，其实你如果更新了脚本，是不会再出现这种问题的了，我将 Caddy 申请的证书放到 /root/.caddy

原來新腳本已經搞好了，還是大神手速快，牛。上週沒想到要更新腳本，不然也不用自己折騰了，哈哈！

**Comment by jsha** [comment] 2019-10-10 00:45
Hello! I am an engineer at Let's Encrypt. We had some problems because V2Ray was sending us too many requests, and we had to block some V2Ray users. We discussed the problem here: https://community.letsencrypt.org/t/need-unblock-ip/103584.

I think the problem was caused by the `read-only file system` error. I think that error was caused by https://github.com/caddyserver/caddy/pull/2620. I proposed a fix at https://github.com/caddyserver/caddy/pull/2798.

@233boy, you made a fix at https://github.com/233boy/v2ray/commit/5fbdf869180f8d042257c55f8c49446494b370c8#diff-e16fccbf00a60d8781b481f7547dffe5R37-R58. But I am worried that these lines will cause problems in the future:

```
			Restart=always
			RestartSec=3
```

These mean that if there is a problem, Caddy will restart quickly, and send too many requests to Let's Encrypt.

In the [systemd unit provided by Caddy](https://github.com/caddyserver/caddy/blob/master/dist/init/linux-systemd/caddy.service), it has these lines:

```
Restart=on-abnormal
StartLimitIntervalSec=14400
StartLimitBurst=10
```

I think these are better. Could you change these lines?

Even better, could you switch back to the systemd unit provided by Caddy after https://github.com/caddyserver/caddy/pull/2798 is merged?

Thanks,
Jacob

**Comment by jsha** [comment] 2019-10-10 17:06
Now https://github.com/caddyserver/caddy/pull/2798 is merged. Could you please revert 5fbdf86? I think this will prevent problems in the future.

**Comment by 233boy** [comment] 2019-10-11 06:26
@jsha 
Hello,  thanks your report
i has pushed a new update eab6857
thanks :)

**Comment by jsha** [comment] 2019-10-11 06:52
Excellent. Thank you very much.

**Closed** 2019-10-22 23:48 UTC

**Comment by Tiamoer** [comment] 2021-06-23 12:54
服务器在配置文件中设置了日志的属性后，启动报错，启动日志如下：
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ v2ray[1864]: V2Ray 4.34.0 (user) 20210606-232738 (go1.15.9 linux/amd64)
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ v2ray[1864]: A unified platform for anti-censorship.
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ v2ray[1864]: main: failed to create server > v2ray.com/core/app/log: failed to initialize access logger > **open /var/log/v2ray/access.log: read-only file system**
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ systemd[1]: v2ray.service: Start request repeated too quickly.
Jun 23 20:43:09 iZj6cgk4xdpbqgml75awreZ systemd[1]: v2ray.service: Failed with result 'exit-code'
